#!/bin/bash

export EDITOR=nvim
export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -solid \#546e7a
xrdb ~/.Xresources

# For BAT : $(cat /sys/class/power_supply/BAT0/capacity)
while true;
do
	xsetroot -name "$(date '+%a, %d %b %H:%M')"
	sleep 1m
done &

# compton &
# feh --bg-scale ~/.cache/wallpaper.jpg &
xwinwrap -ov -ni -fs -- mpv -wid WID --keepaspect=no --loop ~/.cache/gifs/pixels10.gif &

# if dwm crashes, relaunch
# if I exit dwm, close
while true ; do
    exec dwm && break || continue
done > /dev/null 2> /tmp/dwm_err.log