#!/bin/bash

export EDITOR=nvim
export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -solid \#546e7a
xrdb ~/.Xresources

# For BAT : $(cat /sys/class/power_supply/BAT0/capacity)
while true;
do
	xsetroot -name "$(date '+%a, %d %b %H:%M')"
	sleep 1m
done &

exec dwm
